### ISSUE TITLE
Publish a Plugin link broken

### ISSUE THREAD

**Issue by mikeumus** [GitbookIO/help.gitbook.com#17]
The Publish a Plugin link is broken at: 
- https://plugins.gitbook.com/

It maybe wants to link to here:
- http://toolchain.gitbook.com/plugins/create.html

I couldn't find a `plugins.gitbook.com` repo so I couldn't do the pull-request myself. Hope this helps. 

:)

**Comment by Soreine** [comment]
Thanks :)
